# ============================
# AI Provider
# ============================

ai.provider=ollama
#ai.provider=openai

# ============================
# Ollama Configuration
# ============================

ollama.url=http://localhost:11434/api/generate
ollama.model=qwen2.5:7b


# ============================
# OpenAI Configuration
# ============================

openai.url=https://api.openai.com/v1/responses
openai.api.key=YOUR_OPENAI_API_KEY
openai.model=gpt-5

# copilot
copilot.model=gpt-4.1